export default [
  { value: 'MST', name: 'Master' },
  { value: 'C/O', name: 'Chief Officer' },
  { value: '2/0', name: 'Second Officer' },
  { value: '3/0', name: 'Third Officer' },
  { value: 'A/B', name: 'Able Seaman' },
  { value: 'O/S', name: 'Ordinary Seaman' },
  { value: 'D/C', name: 'Deck Cadet' },
  { value: 'D/T', name: 'Deck Trainee' },
  { value: 'C/E', name: 'Chief Engineer' },
  { value: '2/E', name: 'Second Engineer' },
  { value: '3/E', name: 'Third Engineer' },
  { value: '4/E', name: 'Fourth Engineer' },
  { value: 'FTR', name: 'Fitter' },
  { value: 'OLR', name: 'Oiler' },
  { value: 'WPR', name: 'Wiper' },
  { value: 'E/T', name: 'Engine Trainee' },
  { value: 'E/C', name: 'Engine Cadet' },
  { value: 'C/C', name: 'Chief Cook' },
  { value: 'MSM', name: 'Mesman' },
];
