export const vesselType = [
	{ name: 'Cargo Ship', value: 'Cargo Ship' },
	{ name: 'Bulk Carrier', value: 'Bulk Carrier' },
	{ name: 'Container Ship', value: 'Container Ship' },
	{ name: 'Auto Carrier', value: 'Auto Carrier' },
	{ name: 'Tanker', value: 'Tanker' },
	{ name: 'Fishing Vessel', value: 'Fishing Vessel' },
	{ name: 'Oil Industry Vessel', value: 'Oil Industry Vessel' },
	{ name: 'Passenger Ship', value: 'Passenger Ship' },
	{ name: 'Ferryboat', value: 'Ferryboat' },
	{ name: 'Chemical Tanker', value: 'Chemical Tanker' },
	{ name: 'Crude Oil Tanker', value: 'Crude Oil Tanker' },
	{ name: 'Heavy Lift', value: 'Heavy Lift' },
	{ name: 'Offshore Vessel', value: 'Offshore Vessel' },
	{ name: 'Tug Boat', value: 'Tug Boat' },
	{ name: 'Supply Ship', value: 'Supply Ship' },
	{ name: 'Yacht', value: 'Yacht' },
	{ name: 'Barge', value: 'Barge' },
	{ name: 'LPG', value: 'LPG' },
	{ name: 'PCC', value: 'PCC' },
	{ name: 'LCT', value: 'LCT' },
	{ name: 'AHTS', value: 'AHTS' },
	{ name: 'Product Tanker', value: 'Product Tanker' },
	{ name: 'Oil Chemical Tanker', value: 'Oil Chemical Tanker' },
	{ name: 'Oil Tanker', value: 'Oil Tanker' },
];
